# Generated by Django 6.0 on 2026-01-09 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Familya',
            new_name='familya',
        ),
    ]
